content = open('templates/index.html', 'r', encoding='utf-8').read()
content = content.replace('href="https://web-production-5f0e2.up.railway.app" class="btn-dark"', 'href="#" onclick="toggleChat();return false;" class="btn-dark"')
content = content.replace('href="https://web-production-5f0e2.up.railway.app" class="nav-cta"', 'href="#" onclick="toggleChat();return false;" class="nav-cta"')
open('templates/index.html', 'w', encoding='utf-8').write(content)
print('OK - Botones arreglados!')